name: Workflow A

on:
  workflow_dispatch:
    inputs:
      skip_job1:
        required: true
        type: boolean
        default: false

jobs:
  wf_a_job1:
    if: ${{ ! inputs.skip_job1 }}
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: echo 'Job1 done.'

  wf_a_job2:
    runs-on: ubuntu-20.04
    needs:
      - wf_a_job1
    if: ${{ inputs.skip_job1 || success() }}
    steps:
      - name: Echo
        run: echo 'Job2 done.'
